### ISSUE TITLE
SV 1.6.14 DialogBoxGreen removed

### ISSUE THREAD

**Issue by jfCarabias** [Alphablackwolf/SkillPrestige#26]
Hi,
Thank you for the amazing work you've done with the Skill Prestige mod! 
I encountered an issue when using the mod with the latest version of Stardew Valley (1.6.14). It seems the texture LooseSprites/DialogBoxGreen is no longer available in the game, which causes the mod to crash when trying to load it.

I believe this could be resolved by replacing DialogBoxGreen with another existing texture but I don't really know if it is possible.

Issue:
[Skill Prestige] This mod failed in the GameLoop.GameLaunched event. Technical details:
Microsoft.Xna.Framework.Content.ContentLoadException: The content file was not found.
 ---> FileNotFoundException: Could not find file 'C:\Program Files (x86)\Steam\steamapps\common\Stardew Valley\Content\LooseSprites\DialogBoxGreen.xnb'.
File name: 'C:\Program Files (x86)\Steam\steamapps\common\Stardew Valley\Content\LooseSprites\DialogBoxGreen.xnb'
   at Microsoft.Win32.SafeHandles.SafeFileHandle.CreateFile(String fullPath, FileMode mode, FileAccess access, FileShare share, FileOptions options)
   at Microsoft.Win32.SafeHandles.SafeFileHandle.Open(String fullPath, FileMode mode, FileAccess access, FileShare share, FileOptions options, Int64 preallocationSize)
   at System.IO.Strategies.OSFileStreamStrategy..ctor(String path, FileMode mode, FileAccess access, FileShare share, FileOptions options, Int64 preallocationSize)
   at Microsoft.Xna.Framework.TitleContainer.PlatformOpenStream(String safeName) in D:\GitlabRunner\builds\Gq5qA5P4\0\ConcernedApe\stardewvalley\MonoGame.Desktop\MonoGame.Framework\Platform\TitleContainer.Desktop.cs:line 29
   at Microsoft.Xna.Framework.TitleContainer.OpenStream(String name) in D:\GitlabRunner\builds\Gq5qA5P4\0\ConcernedApe\stardewvalley\MonoGame.Desktop\MonoGame.Framework\TitleContainer.cs:line 37
   at Microsoft.Xna.Framework.Content.ContentManager.OpenStream(String assetName) in D:\GitlabRunner\builds\Gq5qA5P4\0\ConcernedApe\stardewvalley\MonoGame.Desktop\MonoGame.Framework\Content\ContentManager.cs:line 276
   --- End of inner exception stack trace ---
   at Microsoft.Xna.Framework.Content.ContentManager.OpenStream(String assetName) in D:\GitlabRunner\builds\Gq5qA5P4\0\ConcernedApe\stardewvalley\MonoGame.Desktop\MonoGame.Framework\Content\ContentManager.cs:line 289
   at Microsoft.Xna.Framework.Content.ContentManager.ReadAsset[T](String assetName, Action`1 recordDisposableObject) in D:\GitlabRunner\builds\Gq5qA5P4\0\ConcernedApe\stardewvalley\MonoGame.Desktop\MonoGame.Framework\Content\ContentManager.cs:line 319
   at Microsoft.Xna.Framework.Content.ContentManager.Load[T](String assetName) in D:\GitlabRunner\builds\Gq5qA5P4\0\ConcernedApe\stardewvalley\MonoGame.Desktop\MonoGame.Framework\Content\ContentManager.cs:line 255
   at StardewModdingAPI.Framework.ContentManagers.BaseContentManager.RawLoad[T](IAssetName assetName, Boolean useCache) in /home/pathoschild/git/SMAPI/src/SMAPI/Framework/ContentManagers/BaseContentManager.cs:line 340
   at StardewModdingAPI.Framework.ContentManagers.GameContentManager.<>c__DisplayClass6_0`1.<LoadExact>b__0() in /home/pathoschild/git/SMAPI/src/SMAPI/Framework/ContentManagers/GameContentManager.cs:line 127
   at StardewModdingAPI.Framework.Utilities.ContextHash`1.Track[TResult](T key, Func`1 action) in /home/pathoschild/git/SMAPI/src/SMAPI/Framework/Utilities/ContextHash.cs:line 53
   at StardewModdingAPI.Framework.ContentManagers.GameContentManager.LoadExact[T](IAssetName assetName, Boolean useCache)
   at StardewModdingAPI.Framework.ContentManagers.BaseContentManager.LoadLocalized[T](IAssetName assetName, LanguageCode language, Boolean useCache) in /home/pathoschild/git/SMAPI/src/SMAPI/Framework/ContentManagers/BaseContentManager.cs:line 154
   at StardewModdingAPI.Framework.ContentManagers.BaseContentManager.Load[T](String assetName, LanguageCode language) in /home/pathoschild/git/SMAPI/src/SMAPI/Framework/ContentManagers/BaseContentManager.cs:line 137
   at SkillPrestige.ModEntry.LoadSprites() in C:\Users\Chris\Source\Repos\SkillPrestige\SkillPrestige\ModEntry.cs:line 306
   at SkillPrestige.ModEntry.OnGameLaunched(Object sender, GameLaunchedEventArgs e) in C:\Users\Chris\Source\Repos\SkillPrestige\SkillPrestige\ModEntry.cs:line 322
   at StardewModdingAPI.Framework.Events.ManagedEvent`1.Raise(TEventArgs args) in /home/pathoschild/git/SMAPI/src/SMAPI/Framework/Events/ManagedEvent.cs:line 101

**Comment by fearvector** [comment]
The **DialogBoxGreen.xnb** error can be resolved by placing it in the **\Stardew Valley\Content\LooseSprites** folder. You can 
 get get the file from the [this link](https://www.file-upload.net/en/download-15409146/DialogBoxGreen.xnb.html) that i got of a post on the mods Nexus Mods page.

But after that it will run into this error when interacting with the statue:
```
[Skill Prestige] This mod failed in the Input.ButtonPressed event. Technical details:
ArgumentNullException: Value cannot be null. (Parameter 'source')
   at System.Linq.ThrowHelper.ThrowArgumentNullException(ExceptionArgument argument)
   at System.Linq.Enumerable.Any[TSource](IEnumerable`1 source, Func`2 predicate)
   at SkillPrestige.Framework.Menus.Elements.PrestigableSkillButtonSet.LoadElements() in C:\Users\Chris\Source\Repos\SkillPrestige\SkillPrestige\Framework\Menus\Elements\PrestigableSkillButtonSet.cs:line 73
   at SkillPrestige.Framework.Menus.Elements.PrestigableSkillButtonSet..ctor(Skill skill, Int32 position, Int32 width, IClickableMenu parentMenu) in C:\Users\Chris\Source\Repos\SkillPrestige\SkillPrestige\Framework\Menus\Elements\PrestigableSkillButtonSet.cs:line 61
   at SkillPrestige.Framework.Menus.SelectionMenu.<LoadSkillPrestigeButtonSets>b__10_0(Skill skill, Int32 index) in C:\Users\Chris\Source\Repos\SkillPrestige\SkillPrestige\Framework\Menus\SelectionMenu.cs:line 55
   at System.Linq.Enumerable.SelectIterator[TSource,TResult](IEnumerable`1 source, Func`3 selector)+MoveNext()
   at System.Collections.Generic.List`1..ctor(IEnumerable`1 collection)
   at SkillPrestige.Framework.Menus.SelectionMenu.LoadSkillPrestigeButtonSets() in C:\Users\Chris\Source\Repos\SkillPrestige\SkillPrestige\Framework\Menus\SelectionMenu.cs:line 55
   at SkillPrestige.Framework.Menus.SelectionMenu..ctor(Rectangle bounds) in C:\Users\Chris\Source\Repos\SkillPrestige\SkillPrestige\Framework\Menus\SelectionMenu.cs:line 37
   at SkillPrestige.ModEntry.OpenSelectionMenu(Boolean playSound) in C:\Users\Chris\Source\Repos\SkillPrestige\SkillPrestige\ModEntry.cs:line 131
   at SkillPrestige.ModEntry.OnButtonPressed(Object sender, ButtonPressedEventArgs e) in C:\Users\Chris\Source\Repos\SkillPrestige\SkillPrestige\ModEntry.cs:line 111
   at StardewModdingAPI.Framework.Events.ManagedEvent`1.Raise(TEventArgs args) in /home/pathoschild/git/SMAPI/src/SMAPI/Framework/Events/ManagedEvent.cs:line 10
```1
